# Generated by Django 4.2.4 on 2023-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0002_alter_advuser_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='birthday_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
