# Generated by Django 4.2.4 on 2023-08-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0003_alter_advuser_birthday_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'verbose_name': 'Вид тренировки', 'verbose_name_plural': 'Виды тренировок'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='cli_num',
            field=models.IntegerField(default=10, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='clients',
            field=models.ManyToManyField(to='tonus.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonus.exercisetype', verbose_name='Вид тренировки'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tonus.trainer', verbose_name='Тренер'),
        ),
    ]
