# Generated by Django 4.2.4 on 2023-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0007_alter_exercise_ex_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='clients',
            field=models.ManyToManyField(related_name='exercises', to='tonus.client', verbose_name='Клиенты'),
        ),
    ]
