# Generated by Django 4.2.4 on 2023-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0009_alter_exercise_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='clients',
            field=models.ManyToManyField(null=True, related_name='exercises', to='tonus.client', verbose_name='Клиенты'),
        ),
    ]
