# Generated by Django 4.2.4 on 2023-09-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0011_alter_exercise_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.TimeField(default='18:15:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(),
        ),
    ]
