# Generated by Django 4.2.4 on 2023-09-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0012_exercise_time_alter_exercise_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('date', 'time'), 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
    ]
