# Generated by Django 4.2.4 on 2023-10-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0013_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='tonus.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(verbose_name='Дата проведения занятия'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Тренировка закончилась'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.TimeField(verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание тренировки'),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='style',
            field=models.TextField(verbose_name='Вид тренировки'),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ClientExerciseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Больше не приду'), (2, 'Не очень'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonus.client', verbose_name='Клиент')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonus.exercise', verbose_name='Тренировка')),
            ],
        ),
    ]
