# Generated by Django 4.2.4 on 2023-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0014_alter_exercise_clients_alter_exercise_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientexerciserelation',
            options={'verbose_name': 'Лайки', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='likers',
            field=models.ManyToManyField(through='tonus.ClientExerciseRelation', to='tonus.client'),
        ),
    ]
