# Generated by Django 4.2.4 on 2023-10-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonus', '0016_alter_advuser_birthday_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientexerciserelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Больше не приду'), (2, 'Не очень'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
    ]
